### ISSUE TITLE
Exact Dependencies

### ISSUE THREAD

**Issue by Frontkick** [Srujan-rai/Diabetic_retinopathy#3]
Hello Srujan your work is very good on diabetic retinopathy 

I am having som issues in installing dependencies, can you provide exact python version you had used at the time of training and using model

**Comment by Srujan-rai** [comment]
The project uses Python 3.10.12. The model was trained on the Google Colab platform, where dependency management was handled seamlessly, ensuring no issues during the training phase.

**Comment by Frontkick** [comment]
Can you share your latest Google Collab link
It would be very helpful
